# This is a basic workflow to help you get started with Actions

name: armTemplateDeployment

on:
  
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_LOUIS_SEB }}

      - name: Deploy Resource Group gr-githubactions with AZ CLI
        uses: Azure/cli@1.0.4
        with:
          inlinescript: az deployment sub create --location "Canada Central" --template-file ./arm/resourcegroup.json

      - name: Deploy Resource Group rg-githubactions
        uses: Azure/arm-deploy@v1
        with: 
          scope: subscription
          subsctiptionId: 61f2b5ea-ab46-4ef9-b648-d3846fd69521 
          region: Canada Central
          template: ./arm/resourcegroup.json
          deploymentName: rg-githubactions
      
      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v1
        with: 
          scope: reosourcegroup
          resourceGroupName: rg-githubactions
          subsctiptionId: 61f2b5ea-ab46-4ef9-b648-d3846fd69521 
          template: ./arm/templates/storageaccount.json
          parameters: ./arm/templates/storageaccount.parameters.=.json
          deploymentMode: incremental
      
          
