# This is a basic workflow to help you get started with Actions

name: armTemplateDeployment

on:
  
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/Login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy Resource Group gr-githubactions with AZ CLI
        uses: Azure/cli@1.0.4
        with:
          inlinescrcipt: |
            az deployment sub create -- location "Canada Central" --template-file ./arm-templates/resourcegroup.json
